version: "2"
services:
  server:
    container_name: back
    restart: always
    build: ./back
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  front:
    container_name: front
    image: linuxserver/nginx
    ports:
      - "8081:80"
    volumes:
       - ./front_nginx:/config

